export const GET_CLIENTS_ACTION = 'GET_CLIENTS_ACTION'
export const SET_CLIENTS_ACTION = 'SET_CLIENTS_ACTION'

export const GET_CLIENT_ACTION = 'GET_CLIENT_ACTION'
export const SET_CLIENT_ACTION = 'SET_CLIENT_ACTION'

export const SEND_CLIENT_ACTION = 'SEND_CLIENT_ACTION'
export const SEND_CLIENT_SUCCESS_ACTION = 'SEND_CLIENT_SUCCESS_ACTION'
export const SEND_CLIENT_FAIL_ACTION = 'SEND_CLIENT_FAIL_ACTION'

export const GET_CONTACT_ACTION = 'GET_CONTACT_ACTION'
export const SET_CONTACT_ACTION = 'SET_CONTACT_ACTION'
export const SEND_CONTACT_ACTION = 'SEND_CONTACT_ACTION'
export const SEND_CONTACT_SUCCESS_ACTION = 'SEND_CONTACT_SUCCESS_ACTION'
export const SEND_CONTACT_FAIL_ACTION = 'SEND_CONTACT_FAIL_ACTION'

export const DELETE_CONTACT_ACTION = 'DELETE_CONTACT_ACTION'
export const DELETE_CONTACT_SUCCESS_ACTION = 'DELETE_CONTACT_SUCCESS_ACTION'
export const DELETE_CONTACT_FAIL_ACTION = 'DELETE_CONTACT_FAIL_ACTION'

export const CREATE_CONTACT_ACTION = 'CREATE_CONTACT_ACTION'
export const CREATE_CONTACT_SUCCESS_ACTION = 'CREATE_CONTACT_SUCCESS_ACTION'
export const CREATE_CONTACT_FAIL_ACTION = 'CREATE_CONTACT_FAIL_ACTION'

export const DELETE_CLIENTS_ACTION = 'DELETE_CLIENTS_ACTION'
export const DELETE_CLIENTS_SUCCESS_ACTION = 'DELETE_CLIENTS_SUCCESS_ACTION'
export const DELETE_CLIENTS_FAIL_ACTION = 'DELETE_CLIENTS_FAIL_ACTION'

export const CREATE_CLIENT_ACTION = 'CREATE_CLIENT_ACTION'
export const CREATE_CLIENT_SUCCESS_ACTION = 'CREATE_CLIENT_SUCCESS_ACTION'
export const CREATE_CLIENT_FAIL_ACTION = 'CREATE_CLIENT_FAIL_ACTION'

export const UPDATE_WITH_CSV_CLIENT_ACTION = 'UPDATE_WITH_CSV_CLIENT_ACTION'
export const UPDATE_WITH_CSV_CLIENT_SUCCESS_ACTION = 'UPDATE_WITH_CSV_CLIENT_SUCCESS_ACTION'
export const UPDATE_WITH_CSV_CLIENT_FAIL_ACTION = 'UPDATE_WITH_CSV_CLIENT_FAIL_ACTION'

export const LOGIN_ACTION = 'LOGIN_ACTION'
export const LOGOUT_ACTION = 'LOGOUT_ACTION'
export const LOGIN_SUCCESS_ACTION = 'LOGIN_SUCCESS_ACTION'
export const LOGIN_FAIL_ACTION = 'LOGIN_FAIL_ACTION'
export const LOGOUT_SUCCESS_ACTION = 'LOGOUT_SUCCESS_ACTION'
export const LOGOUT_FAIL_ACTION = 'LOGOUT_FAIL_ACTION'
